### ISSUE TITLE
Gitignore file not properly formatted for Drupal development projects

### ISSUE THREAD

**Issue by mikemadison13** [acquia/drupal-recommended-project#12]
The gitignore project that ships with drupal-recommended-project makes sense for this repo, but it doesn't make sense for a Drupal project. Specifically:

- it has composer.lock gitignored (bad)
- it is missing all of the local file system ignores (e.g. .DS_Store)
- it duplicates entires for .editorconfig and .gitattributes (which I don't think should be gitignored anyway)

While I can put in a new PR to fix this as discussed @danepowell I think we have a larger problem here (because obviously you want composer.lock git ignored for this project but we don't want to force folks to gitignore this in their builds). So I think we need to tweak something here to get that lined up.

**Comment by danepowell** [comment]
Composer project templates are really hard to get right. I've thought about this and decided to merge the partial fix removing composer.lock in https://github.com/acquia/drupal-recommended-project/pull/16

I definitely don't want to commit composer.lock to _this_ repo because in the absence of daily maintenance, it would lead to customers getting outdated (possibly insecure) packages when creating new projects. composer.lock is something that should exist in downstream projects, but not _this_ repo.

Conversely, there are files (such as .travis.yml and the README) that will exist in this repo that shouldn't exist downstream. That's why this is so hard to get right. 🤷 

In the absence of any clear solution on the Composer front, I think the best we can do is to focus on the end user experience and deal with these issues on a case-by-case basis. In this case, getting composer.lock out of gitignore is right by the user, and we as maintainers just have to be vigilant that it doesn't accidentally get committed.

**Comment by mikemadison13** [comment]
@danepowell what if we leave this as is, and then write a BLT plugin that upon blt settings init overwrites the gitignore with a templated one out of the BLT repo? there is historical precedence for that and it is done elsewhere.

**Comment by grasmash** [comment]
I'd take this approach:

* Create a template.gitignore file with the correct files ignored for a new project
* Add a post-create-project-command script to this composer.json
* In that script, copy template.git ignore to .gitignore

**Comment by danepowell** [comment]
Yeah that's basically what we did with BLT Project. But I don't want to increase the scope of BLT at this point, both for my own sake as maintainer and because that leaves non-BLT users in the cold.

I think the current situation is acceptable, if we get to the point of needing to rewrite files on install we can add a Composer plugin to this template.

(simulpost: basically what Matt suggested 😄 )

**Comment by mikemadison13** [comment]
yeah i think that suggestion works great and doesn't increase the blt footprint while getting us the gitignore file we need. i'm all for it!
