### ISSUE TITLE
Add oomphinc / composer-installers-extender 

### ISSUE THREAD

**Issue by camoa** [acquia/drupal-recommended-project#23]
The tool installs composer/installers, but since we use the installer-type key in the composer.json to be able to bring both bower-asset and npm-asset types of packages, the oomphinc/composer-installers-extender is needed for that to work.

Otherwise all bower-assets and npm-assets will be installed in the vendor folder.

This package was previously brought in by acquia/lightning.

**Comment by danepowell** [comment]
I agree in principle, but I'm a little confused because I cannot reproduce the issue you describe of assets being installed to `vendor`.

Running `composer create-project --no-interaction acquia/drupal-recommended-project` for me puts all npm/bower assets into `docroot/libraries`, as expected.

Can you provide steps to reproduce the issue you're seeing, or explain this discrepancy?

**Comment by danepowell** [comment]
While I don't think this is a bug (I see no immediate consequences either way), I agree that in principle we should depend on composer-installers-extender, so I've added this dependency.
