### ISSUE TITLE
ACMS-1648: Remove scaffolding for the files already done by drupal/core

### ISSUE THREAD

**Issue by chandan-singh7929** [acquia/drupal-recommended-project#283]
Noticed that scaffolding done here https://github.com/acquia/drupal-recommended-project/blob/master/composer.json#L59-L68 is already perform by drupal core.

Also in latest version of acquia cms we don't use it as profiles hence below code can be removed
https://github.com/acquia/drupal-recommended-project/blob/master/composer.json#L71-L74

**Comment by vishalkhode1** [comment]
I think this makes sense to me. We can remove the scaffolding as it's already being done by Drupal core.
> Noticed that scaffolding done here https://github.com/acquia/drupal-recommended-project/blob/master/composer.json#L59-L68 is already perform by drupal core.

@danepowell Any thoughts ?
cc: @secretsayan

**Comment by danepowell** [comment]
It's a reasonable suggestion to remove the scaffold lines for default.settings.php and default.services.yaml, but note that they doesn't strictly duplicate what Drupal core does by default.

Drupal will [overwrite these files if they already exist](https://www.drupal.org/docs/develop/using-composer/using-drupals-composer-scaffold#toc_7). That's why DRP sets `overwrite: false`. If you change this, you should probably also make sure that default.settings.php and default.services.yaml are gitignored, otherwise they are going to change and show as diffs whenever they change upstream, and I think that will annoy people.
